# Generated by Django 6.0 on 2025-12-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0002_rename_muser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
