# Generated by Django 6.0 on 2025-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20),
        ),
    ]
