# Generated by Django 6.0 on 2026-04-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0006_question_topic_answer_question_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
