# Generated by Django 6.0 on 2026-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0010_record_time_alter_record_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystemObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('type_object', models.CharField(max_length=100)),
                ('diametr', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('structure', models.TextField()),
                ('temp', models.CharField(max_length=150)),
                ('features', models.TextField()),
                ('desc', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
