# Generated by Django 6.0 on 2026-05-03 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0013_universesystemobject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedUniverseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('universer_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='space_website.universesystemobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_universe_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['visited_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'universe_object'), name='unique_user_universe_object_visit')],
            },
        ),
    ]
