# Generated by Django 6.0 on 2026-05-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0014_visiteduniverseobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiteduniverseobject',
            old_name='universer_object',
            new_name='universe_object',
        ),
    ]
