# Generated by Django 6.0 on 2026-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0015_rename_universer_object_visiteduniverseobject_universe_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='myth_ab_space')),
                ('name', models.CharField(max_length=150)),
                ('parameters', models.TextField()),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
