# Generated by Django 6.0 on 2026-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0016_mythobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythobject',
            name='model_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mythobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myth_ab_space/'),
        ),
    ]
