# Generated by Django 6.0 on 2026-05-04 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0017_mythobject_model_url_alter_mythobject_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedMythObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('myth_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='space_website.mythobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_myth_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['visited_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'myth_object'), name='unique_user_myth_object_visit')],
            },
        ),
    ]
