# Generated by Django 6.0 on 2026-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0019_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceShips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='skin_ship/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
