# Generated by Django 6.0 on 2026-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0020_spaceships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceships',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
