# Generated by Django 6.0 on 2026-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0022_usership'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
