# Generated by Django 6.0 on 2026-05-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0023_profile_level_profile_total_xp_profile_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_xp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='xp',
        ),
    ]
