# Generated by Django 6.0 on 2026-05-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0025_rank_profile_xp_profile_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='reward_coin',
            new_name='reward_xp',
        ),
    ]
