# Generated by Django 6.0 on 2026-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_website', '0029_completedquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
